import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

export default function Wrapper({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title : 'E-Commerce Website'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-16 items-center justify-between shadow-md px-4">
            <Link href="/">
              <text className="text-3xl font-bold">home.</text>
            </Link>
            <div className="flex">
              <Link href="/cart">
                <p className="p-2">Cart</p>
              </Link>
              <Link href="/checkout">
                <p className="p-2">Login</p>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className='flex justify-center items-center'>footer</footer>
      </div>
    </>
  );
}
