const data = {
  products: [
    {
      name: 'FOUNDATIONS T-SHIRT - BONE',
      slug: 'foundations-tee-bone',
      category: 'Tops',
      image: '/images/foundations-tee-bone.jpg',
      countInStock: 10,
      price: 35,
    },
    {
      name: 'FOUNDATIONS T-SHIRT - BLACK',
      slug: 'foundations-tee-black',
      category: 'Tops',
      image: '/images/foundations-tee-black.jpg',
      countInStock: 12,
      price: 35,
    },
    {
      name: 'FOUNDATIONS T-SHIRT - GREY',
      slug: 'foundations-tee-grey',
      category: 'Tops',
      image: '/images/foundations-tee-grey.jpg',
      countInStock: 8,
      price: 35,
    },
    {
      name: 'FOUNDATIONS CREWNECK - ALPINE',
      slug: 'foundations-crewneck-alpine',
      category: 'Tops',
      image: '/images/foundations-crewneck-alpine.jpg',
      countInStock: 35,
      price: 85,
    },
    {
      name: 'FOUNDATIONS CREWNECK - BLACK',
      slug: 'foundations-crewneck-black',
      category: 'Tops',
      image: '/images/foundations-crewneck-black.jpg',
      countInStock: 40,
      price: 85,
    },
    {
      name: 'FOUNDATIONS CREWNECK - GREY',
      slug: 'foundations-crewneck-grey',
      category: 'Tops',
      image: '/images/foundations-crewneck-grey.jpg',
      countInStock: 40,
      price: 85,
    },
    {
      name: 'FOUNDATIONS NYLON PANT - ALPINE',
      slug: 'foundations-nylon-pant-alpine',
      category: 'Tops',
      image: '/images/foundations-nylon-pant-alpine.jpg',
      countInStock: 20,
      price: 85,
    },
    {
      name: 'FOUNDATIONS NYLON PANT - BLACK',
      slug: 'foundations-nylon-pant-black',
      category: 'Tops',
      image: '/images/foundations-nylon-pant-black.jpg',
      countInStock: 25,
      price: 85,
    },
    {
      name: 'FOUNDATIONS NYLON PANT - RED',
      slug: 'foundations-nylon-pant-red',
      category: 'Tops',
      image: '/images/foundations-nylon-pant-red.jpg',
      countInStock: 30,
      price: 85,
    },
    {
      name: 'FOUNDATIONS NYLON SHORT - RED',
      slug: 'foundations-nylon-short-red',
      category: 'Tops',
      image: '/images/foundations-nylon-short-red.jpg',
      countInStock: 15,
      price: 68,
    },
    {
      name: 'FOUNDATIONS NYLON SHORT - ROYAL',
      slug: 'foundations-nylon-short-royal',
      category: 'Tops',
      image: '/images/foundations-nylon-short-royal.jpg',
      countInStock: 12,
      price: 68,
    },
    {
      name: 'FOUNDATIONS NYLON SHORT - ALPINE',
      slug: 'foundations-nylon-short-alpine',
      category: 'Tops',
      image: '/images/foundations-nylon-short-alpine.jpg',
      countInStock: 18,
      price: 68,
    },
  ],
};

export default data;
